model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: ${OPENAI_API_KEY}
  
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: ${OPENAI_API_KEY}
      
  - model_name: gpt-4.5-preview
    litellm_params:
      model: gpt-4.5-preview
      api_key: ${OPENAI_API_KEY}
