model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: ${OPENAI_API_KEY}
  
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: ${OPENAI_API_KEY}

general_settings:
  proxy_assistant_api: true
  port: ${PORT:-7860}
  host: 0.0.0.0

environment_variables:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
