model_list:
  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1

  # - model_name: gpt-4o-2024-11-20
  #   litellm_params:
  #     model: openai/gpt-4o-2024-11-20

  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini

assistant_settings:
  custom_llm_provider: openai
  litellm_params: 
    api_key: os.environ/OPENAI_API_KEY